### PR TITLE
Https patch

### PR DESCRIPTION
**Pull request by fgleixner**
This patch enables the automatic configuration of https for folio using the stripes docker image (testes) and the nginx installation method (to be tested). Also extended some documentation and the folio playbook to include securing the supertenant.

### CODE REVIEW

**Comment by wafschneider** [comment]
Thanks, @fgleixner -- we'll review this PR next week. The stripes-docker role is used quite a bit in the FOLIO CI processes, so we'll have to do some testing.

**Comment by fgleixner** [comment]
OK, then you should check if the change in stripes-docker concerning the variable rename from stripes_port to stripes_listen_port harms the CI process. The intention was to use one variable name for the same thing - docker or non-docker nginx installation.

**Review by funkymalc — CHANGES_REQUESTED** [review]
- 'stripes_port' should be changed to 'stripes_listen_port' in group_vars/vagrant.  I will update that in a separate folio-ansible PR.  

- there are a couple of playbooks in the folio-infrastructure repo (which includes folio-ansible as a submodule) that set 'stripes_port'.  These will need to be updated to stripes_listen_port in a separate PR for that repo.   I will make that change separately and time the merge with the merge of this PR.

**Comment by funkymalc** [comment]
Changes in this PR have been incorporated into PR-402.  Closing.

**Pull request closed without merging**
